name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: Install dependencies in api
        run: |
          cd ./Application/api
          npm install npm@9.6.1
          
      - name: Install dependencies in frontend dir
        run: |
         cd ./Application/api/helloworldvue
         npm install npm@9.6.1
         
      - name: build frontend
        run: |
         cd ./Application/api/helloworldvue
         npm run build
         npm run lint
        
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false
        id: create_release
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            $(echo ./dist/*)
          asset_name: my-app-refs/${{ github.ref }}/v0.1.2.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          shell: bash
