name: Frontend Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  frontend-ci-test:

    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies in api
      run: |
        cd ./Application/api
        npm install npm@9.6.1


    - name: Install dependencies in frontend dir
      run: |
        cd ./Application/api/helloworldvue
        npm install npm@9.6.1
        npm run build
        npm run lint
        
    - name: build frontend
      run: |
        cd ./Application/api/helloworldvue
        npm run build
        npm run lint
